### ISSUE TITLE
Multiple definition errors due to non-standard naming convention

### ISSUE THREAD

**Issue by VladimirGaristov** [khoih-prog/WebSockets2_Generic#21]
Hello,
First of all, thank you for your work on this very useful library.
As several people have already pointed out in #3 and #15, using WebSockets2_Generic in a project that consists of multiple source files can lead to "multiple definition" errors while linking. The reason for this is that most of the code in this library is inside .hpp files which are #include-ed. This is not standard practice - in C++ source code should be in .cpp files which do not get #include-ed but instead are linked together after compilation by the linker. 
Do you have a good reason to break such a fundamental C++ convention? If not, can you please rename your source files to *.cpp to prevent linking errors? This is the only issue that stops me from recommending this library as the best websocket library for embedded projects.

**Comment by khoih-prog** [comment]
Hi,

First, thanks for your interest in the library.

There are many reasons the header-only libraries are **more and more popular and useful**, and I think you have to be prepared to adapt to the new way.

Please research on Google why. But **don't immediately trust** all the (many outdated) posts there yet, but you have to test and verify why and **what are the benefits of header-only libraries**. I certainly know enough and know why I prefer this header-only way Anything new certainly will suffers certain `critics`, but the price to pay is much less than the benefits.

You can have a look at these widely-used and complex libraries, using header-only approach

1. [**SinricPro**](https://github.com/sinricpro/esp8266-esp32-sdk)
2. [**Blynk**](https://github.com/blynkkk/blynk-library)

and many more to count

Normally, you get the error because of **careless inclusion of any header file in any place.**

I also guess you, as an experienced programmer, can know how easy to just spend 5 minutes to **modify/rename** some of the hpp files to cpp files, if you don't know how to solve to real problem of "multiple definition" errors.

If un-experienced users request this, I'll possibly think about adding the cpp-version besides the h-only version. For example the [**AsyncHTTPRequest_Generic** library](https://github.com/khoih-prog/AsyncHTTPRequest_Generic) and many more.

Good Luck,
