### ISSUE TITLE
Endless loop reading line from client

### ISSUE THREAD

**Issue by izikkhv** [khoih-prog/WebSockets2_Generic#27]
Teensy41_NativeEthernet_tcp.hpp, line 103:
 WSString readLine() override   {
      WSString line = "";
      int ch = -1;
      while ( ch != '\n' && available()) {
           // It is important to call `client.available()`. Otherwise no data can be read.
           if (client.available())   {
                ch = client.read();
                if (ch >= 0)  {
                     line += (char) ch;
                }
            }
     }
     return line;
 }

sometimes client.available() return false, but available() still true then the loop is endless

**Comment by khoih-prog** [comment]
Thanks for your interest in the library.

Please follow the instructions in [**Issue: Bug report**](https://github.com/khoih-prog/WebSockets2_Generic/issues/new?assignees=&labels=&template=bug_report.md&title=) and provide at leas the [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example) so that anyone can verify it it's a real issue.

Also noted that Teensy 4.1 [**NativeEthernet**](https://github.com/vjmuzik/NativeEthernet) is still in infancy and buggy state, and check if there is any issue of that library.

I'll reopen the issue when the bug is proven.

Good Luck,
